export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const ADD_COMPLAINT = 'ADD_COMPLAINT';
export const GET_COMPLAINTS = 'GET_COMPLAINTS';
export const GET_COMPLAINT = 'GET_COMPLAINT';
export const COMPLAINT_ERROR = 'COMPLAINT_ERROR';
export const UPDATE_COMPLAINT = 'UPDATE_COMPLAINT';
export const DELETE_COMPLAINT = 'DELETE_COMPLAINT';

export const GET_USERS = 'GET_USERS';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const ADMIN_ERROR = 'COMPLAINT_ERROR';